KNN

In [23]:
import pandas as pd
import sqlite3 as sq

url_1 = 'https://raw.githubusercontent.com/4GeeksAcademy/k-nearest-neighbors-project-tutorial/main/tmdb_5000_movies.csv'
url_2 = 'https://raw.githubusercontent.com/4GeeksAcademy/k-nearest-neighbors-project-tutorial/main/tmdb_5000_credits.csv'

movies = pd.read_csv(url_1, sep=',')
credits = pd.read_csv(url_2, sep=',')
movies.to_csv('/workspaces/KNN/data/raw/movies.csv', index=False)
credits.to_csv('/workspaces/KNN/data/raw/credits.csv', index=False)

In [24]:
movies.info

<bound method DataFrame.info of          budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
...         ...                                                ...
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799       9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800          0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801          0                                                 []
4802          0                [{"id": 99, "name": "Documentary"}]

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995
1          http://disney.go.com/disneypictures/pirates/     285
2           http://www.sonypictures.com/movies/spectre/  206647
3                    http://www.thedarkknightrises.com/   49026
4                  http://movies.disney.com/john-carter   49529
...                                                 ...     ...
4798                                                NaN    9367
4799                                                NaN   72766
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617
4801                        http://shanghaicalling.com/  126186
4802                                                NaN   25975

                                               keywords original_language  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...                en
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...                en
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...                en
4     [{"id": 818, "name": "based on novel"}, {"id":...                en
...                                                 ...               ...
4798  [{"id": 5616, "name": "united states\u2013mexi...                es
4799                                                 []                en
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...                en
4801                                                 []                en
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...                en

                                original_title  \
0                                       Avatar
1     Pirates of the Caribbean: At World's End
2                                      Spectre
3                        The Dark Knight Rises
4                                  John Carter
...                                        ...
4798                               El Mariachi
4799                                 Newlyweds
4800                 Signed, Sealed, Delivered
4801                          Shanghai Calling
4802                         My Date with Drew

                                               overview  popularity  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577
1     Captain Barbossa, long believed to be dead, ha...  139.082615
2     A cryptic message from Bondâ€™s past sends him o...  107.376788
3     Following the death of District Attorney Harve...  112.312950
4     John Carter is a war-weary, former military ca...   43.926995
...                                                 ...         ...
4798  El Mariachi just wants to play his guitar and ...   14.269792
4799  A newlywed couple's honeymoon is upended by th...    0.642552
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476
4801  When ambitious New York attorney Sam is sent t...    0.857008
4802  Ever since the second grade when he first saw ...    1.929883

                                   production_companies  \
0     [{"name": "Ingenious Film Partners", "id": 289...
1     [{"name": "Walt Disney Pictures", "id": 2}, {"...
2     [{"name": "Columbia Pictures", "id": 5}, {"nam...
3     [{"name": "Legendary Pictures", "id": 923}, {"...
4           [{"name": "Walt Disney Pictures", "id": 2}]
...                                                 ...
4798           [{"name": "Columbia Pictures", "id": 5}]
4799                                                 []
4800  [{"name": "Front Street Pictures", "id": 3958}...
4801                                                 []
4802  [{"name": "rusty bear entertainment", "id": 87...

                                   production_countries release_date  \
0     [{"iso_3166_1": "US", "name": "United States o...   2009-12-10
1     [{"iso_3166_1": "US", "name": "United States o...   2007-05-19
2     [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26
3     [{"iso_3166_1": "US", "name": "United States o...   2012-07-16
4     [{"iso_3166_1": "US", "name": "United States o...   2012-03-07
...                                                 ...          ...
4798  [{"iso_3166_1": "MX", "name": "Mexico"}, {"iso...   1992-09-04
4799                                                 []   2011-12-26
4800  [{"iso_3166_1": "US", "name": "United States o...   2013-10-13
4801  [{"iso_3166_1": "US", "name": "United States o...   2012-05-03
4802  [{"iso_3166_1": "US", "name": "United States o...   2005-08-05

         revenue  runtime                                   spoken_languages  \
0     2787965087    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...
1      961000000    169.0           [{"iso_639_1": "en", "name": "English"}]
2      880674609    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...
3     1084939099    165.0           [{"iso_639_1": "en", "name": "English"}]
4      284139100    132.0           [{"iso_639_1": "en", "name": "English"}]
...          ...      ...                                                ...
4798     2040920     81.0      [{"iso_639_1": "es", "name": "Espa\u00f1ol"}]
4799           0     85.0                                                 []
4800           0    120.0           [{"iso_639_1": "en", "name": "English"}]
4801           0     98.0           [{"iso_639_1": "en", "name": "English"}]
4802           0     90.0           [{"iso_639_1": "en", "name": "English"}]

        status                                            tagline  \
0     Released                        Enter the World of Pandora.
1     Released     At the end of the world, the adventure begins.
2     Released                              A Plan No One Escapes
3     Released                                    The Legend Ends
4     Released               Lost in our world, found in another.
...        ...                                                ...
4798  Released  He didn't come looking for trouble, but troubl...
4799  Released  A newlywed couple's honeymoon is upended by th...
4800  Released                                                NaN
4801  Released                           A New Yorker in Shanghai
4802  Released                                                NaN

                                         title  vote_average  vote_count
0                                       Avatar           7.2       11800
1     Pirates of the Caribbean: At World's End           6.9        4500
2                                      Spectre           6.3        4466
3                        The Dark Knight Rises           7.6        9106
4                                  John Carter           6.1        2124
...                                        ...           ...         ...
4798                               El Mariachi           6.6         238
4799                                 Newlyweds           5.9           5
4800                 Signed, Sealed, Delivered           7.0           6
4801                          Shanghai Calling           5.7           7
4802                         My Date with Drew           6.3          16

[4803 rows x 20 columns]>

In [25]:
movies.shape

(4803, 20)

In [26]:
credits.info

<bound method DataFrame.info of       movie_id                                     title  \
0        19995                                    Avatar
1          285  Pirates of the Caribbean: At World's End
2       206647                                   Spectre
3        49026                     The Dark Knight Rises
4        49529                               John Carter
...        ...                                       ...
4798      9367                               El Mariachi
4799     72766                                 Newlyweds
4800    231617                 Signed, Sealed, Delivered
4801    126186                          Shanghai Calling
4802     25975                         My Date with Drew

                                                   cast  \
0     [{"cast_id": 242, "character": "Jake Sully", "...
1     [{"cast_id": 4, "character": "Captain Jack Spa...
2     [{"cast_id": 1, "character": "James Bond", "cr...
3     [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4     [{"cast_id": 5, "character": "John Carter", "c...
...                                                 ...
4798  [{"cast_id": 1, "character": "El Mariachi", "c...
4799  [{"cast_id": 1, "character": "Buzzy", "credit_...
4800  [{"cast_id": 8, "character": "Oliver O\u2019To...
4801  [{"cast_id": 3, "character": "Sam", "credit_id...
4802  [{"cast_id": 3, "character": "Herself", "credi...

                                                   crew
0     [{"credit_id": "52fe48009251416c750aca23", "de...
1     [{"credit_id": "52fe4232c3a36847f800b579", "de...
2     [{"credit_id": "54805967c3a36829b5002c41", "de...
3     [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...                                                 ...
4798  [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4799  [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4800  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4801  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4802  [{"credit_id": "58ce021b9251415a390165d9", "de...

[4803 rows x 4 columns]>

In [27]:
credits.shape

(4803, 4)

CREAR LA BASE DE DATOS EN SQL

In [28]:
import sqlite3

conn = sqlite3.connect("../data/movies_database.db")

print(movies.to_sql("movies_table", conn, if_exists = "replace", index = False))
print(credits.to_sql("credits_table", conn, if_exists = "replace", index = False))

4803
4803

In [40]:
query = """
    SELECT *
    FROM movies_table
    INNER JOIN credits_table
    ON movies_table.title = credits_table.title;
"""

total_data = pd.read_sql_query(query, conn)
conn.close()

total_data = total_data.loc[:, ~total_data.columns.duplicated()]
total_data.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [41]:
import pandas as pd
import json

def load_json_safe(json_str):
    """Intenta cargar una cadena JSON. Si falla, devuelve una lista vacÃ­a."""
    try:
        return json.loads(json_str)
    except (TypeError, json.JSONDecodeError):
        return []

def process_list(json_str, key, limit=None):
    """Procesa una cadena JSON y devuelve una lista de valores para la clave dada."""
    data = load_json_safe(json_str)
    if limit:
        return [item[key] for item in data[:limit] if key in item]
    return [item[key] for item in data if key in item]

def process_genres(genres_str):
    """Procesa la cadena de gÃ©neros y devuelve una lista de nombres de gÃ©neros."""
    return process_list(genres_str, 'name')

def process_keywords(keywords_str):
    """Procesa la cadena de palabras clave y devuelve una lista de ellas."""
    return process_list(keywords_str, 'name')

def process_cast(cast_str):
    """Procesa la cadena de reparto y devuelve una lista con los nombres de los tres primeros actores."""
    return process_list(cast_str, 'name', limit=3)

def process_crew(crew_str):
    """Procesa la cadena del equipo y devuelve los nombres de los directores."""
    directors = process_list(crew_str, 'name')
    return ' '.join(directors)

def process_overview(overview_str):
    """Envuelve el resumen en una lista."""
    return [overview_str] if overview_str else []

# Aplicar las funciones al DataFrame
total_data['genres'] = total_data['genres'].apply(process_genres)
total_data['keywords'] = total_data['keywords'].apply(process_keywords)
total_data['cast'] = total_data['cast'].apply(process_cast)
total_data['crew'] = total_data['crew'].apply(process_crew)
total_data['overview'] = total_data['overview'].apply(process_overview)

# Verificar las primeras filas del DataFrame
print(total_data.head())

      budget                                         genres  \
0  237000000  [Action, Adventure, Fantasy, Science Fiction]
1  300000000                   [Adventure, Fantasy, Action]
2  245000000                     [Action, Adventure, Crime]
3  250000000               [Action, Crime, Drama, Thriller]
4  260000000           [Action, Adventure, Science Fiction]

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995
1  http://disney.go.com/disneypictures/pirates/     285
2   http://www.sonypictures.com/movies/spectre/  206647
3            http://www.thedarkknightrises.com/   49026
4          http://movies.disney.com/john-carter   49529

                                            keywords original_language  \
0  [culture clash, future, space war, space colon...                en
1  [ocean, drug abuse, exotic island, east india ...                en
2  [spy, based on novel, secret agent, sequel, mi...                en
3  [dc comics, crime fighter, terrorist, secret i...                en
4  [based on novel, mars, medallion, space travel...                en

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview  popularity  \
0  [In the 22nd century, a paraplegic Marine is d...  150.437577
1  [Captain Barbossa, long believed to be dead, h...  139.082615
2  [A cryptic message from Bondâ€™s past sends him ...  107.376788
3  [Following the death of District Attorney Harv...  112.312950
4  [John Carter is a war-weary, former military c...   43.926995

                                production_companies  ... runtime  \
0  [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...   169.0
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...  ...   148.0
3  [{"name": "Legendary Pictures", "id": 923}, {"...  ...   165.0
4        [{"name": "Walt Disney Pictures", "id": 2}]  ...   132.0

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1           [{"iso_639_1": "en", "name": "English"}]  Released
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3           [{"iso_639_1": "en", "name": "English"}]  Released
4           [{"iso_639_1": "en", "name": "English"}]  Released

                                          tagline  \
0                     Enter the World of Pandora.
1  At the end of the world, the adventure begins.
2                           A Plan No One Escapes
3                                 The Legend Ends
4            Lost in our world, found in another.

                                      title vote_average vote_count movie_id  \
0                                    Avatar          7.2      11800    19995
1  Pirates of the Caribbean: At World's End          6.9       4500      285
2                                   Spectre          6.3       4466   206647
3                     The Dark Knight Rises          7.6       9106    49026
4                               John Carter          6.1       2124    49529

                                               cast  \
0  [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1     [Johnny Depp, Orlando Bloom, Keira Knightley]
2      [Daniel Craig, Christoph Waltz, LÃ©a Seydoux]
3      [Christian Bale, Michael Caine, Gary Oldman]
4    [Taylor Kitsch, Lynn Collins, Samantha Morton]

                                                crew
0  Stephen E. Rivkin Rick Carter Christopher Boye...
1  Dariusz Wolski Gore Verbinski Jerry Bruckheime...
2  Thomas Newman Sam Mendes Anna Pinnock John Log...
3  Hans Zimmer Charles Roven Christopher Nolan Ch...
4  Andrew Stanton Andrew Stanton John Lasseter Co...

[5 rows x 23 columns]

In [42]:
total_data["overview"] = total_data["overview"].apply(lambda x: [str(x)])
total_data["genres"] = total_data["genres"].apply(lambda x: [str(genre) for genre in x])
total_data["keywords"] = total_data["keywords"].apply(lambda x: [str(keyword) for keyword in x])
total_data["cast"] = total_data["cast"].apply(lambda x: [str(actor) for actor in x])
total_data["crew"] = total_data["crew"].apply(lambda x: [str(crew_member) for crew_member in x])

total_data["tags"] = total_data["overview"] + total_data["genres"] + total_data["keywords"] + total_data["cast"] + total_data["crew"]
total_data["tags"] = total_data["tags"].apply(lambda x: ",".join(x).replace(",", " "))

total_data.drop(columns = ["genres", "keywords", "cast", "crew", "overview"], inplace = True)

In [34]:
total_data

,budget,homepage,id,original_language,original_title,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,tags
0,237000000,http://www.avatarmovie.com/,19995,en,Avatar,150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,[['In the 22nd century a paraplegic Marine is...
1,300000000,http://disney.go.com/disneypictures/pirates/,285,en,Pirates of the Caribbean: At World's End,139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,[['Captain Barbossa long believed to be dead ...
2,245000000,http://www.sonypictures.com/movies/spectre/,206647,en,Spectre,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,[['A cryptic message from Bondâ€™s past sends hi...
3,250000000,http://www.thedarkknightrises.com/,49026,en,The Dark Knight Rises,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[[""Following the death of District Attorney Ha..."
4,260000000,http://movies.disney.com/john-carter,49529,en,John Carter,43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[[""John Carter is a war-weary former military..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,None,9367,es,El Mariachi,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,[['El Mariachi just wants to play his guitar a...
4805,9000,None,72766,en,Newlyweds,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[[""A newlywed couple's honeymoon is upended by..."
4806,0,http://www.hallmarkchannel.com/signedsealeddel...,231617,en,"Signed, Sealed, Delivered",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,None,"Signed, Sealed, Delivered",7.0,6,231617,"[['""Signed Sealed Delivered"" introduces a de..."
4807,0,http://shanghaicalling.com/,126186,en,Shanghai Calling,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,[['When ambitious New York attorney Sam is sen...
4808,0,None,25975,en,My Date with Drew,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,None,My Date with Drew,6.3,16,25975,"[[""Ever since the second grade when he first s..."

In [35]:
total_data.iloc[0].tags

"[['In the 22nd century  a paraplegic Marine is dispatched to the moon Pandora on a unique mission  but becomes torn between following orders and protecting an alien civilization.']]"

In [36]:
total_data.iloc[1].tags

"[['Captain Barbossa  long believed to be dead  has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.']]"

In [37]:
total_data.to_csv("../data/processed/clean_data.csv", index = False)

conn = sqlite3.connect("../data/movies_database.db")

total_data.to_sql("clean_movies_data", conn, if_exists = "replace", index = False)

4809

KNN

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(total_data["tags"])

model = NearestNeighbors(n_neighbors = 6, algorithm = "brute", metric = "cosine")
model.fit(tfidf_matrix)

def get_movie_recommendations(movie_title):
    movie_index = total_data[total_data["title"] == movie_title].index[0]
    distances, indices = model.kneighbors(tfidf_matrix[movie_index])
    similar_movies = [(total_data["title"][i], distances[0][j]) for j, i in enumerate(indices[0])]
    return similar_movies[1:]

input_movie = "Harry Potter and the Order of the Phoenix"
recommendations = get_movie_recommendations(input_movie)
print("Film recommendations '{}'".format(input_movie))
for movie, distance in recommendations:
    print("- Film: {}".format(movie))

Film recommendations 'Harry Potter and the Order of the Phoenix'
- Film: Harry Potter and the Chamber of Secrets
- Film: Harry Potter and the Prisoner of Azkaban
- Film: Harry Potter and the Goblet of Fire
- Film: Harry Potter and the Half-Blood Prince
- Film: Harry Potter and the Philosopher's Stone

In [46]:
from pickle import dump

dump(model, open("/workspaces/KNN/models/knn.sav", "wb"))